export const ROUTES = {
  MAIN: "/main",
  SINGIN: "/sign-in",
  SINGUP: "/sign-up",
  MODULE: "/module",
  CREATEMODULE: "/create-module/:id",
  MODULETEST: "/module-test",
  CREATEMODULETEST: "/create-module-test/:id",
  CUSTOMTEST: "/create-custom-test",
  TEST: "/test",
  RESULTS: "/test-results",
  EXPLANATION: "/explanation/:id",
  NOTFOUND: "*",
  PROFILE: '/profile',
  USERS: '/users',
  USERS_DETAIL: '/users/:id',
  SYSTEM: '/system',
  CREATE_SYSTEM: '/create-system/:id',
  TEST_REVIEW: '/test-review',
  GROUP: '/group',
  CREATE_GROUP: '/create-group/:id',
  GROUP_BINDING: '/binding',
  GROUP_BINDING_BINDING: '/create-group-binding/:id',
  VERIFY: '/verify',
  FORGOT: '/forgot',
  NEW_PASSWORD: '/new-password'
};
